### ISSUE TITLE
New car input page

### ISSUE THREAD

**Issue by jdcarey128** [Carbon-Knight/Front-End#18] opened 2021-01-08 21:38 UTC
As a user, when I click on 'Add Car' from the Calculate carbon footprint page, I am taken to a new car form where I see fields for: 
- [x] Make, Model, Year, Fuel Efficiency (MPG), and Fuel Type (drop down: either gasoline or diesel)
- [x] When I click 'Add Vehicle' from the new car page, I am redirected to the Carbon Footprint calculation page. In the Select Car drop down, I see my created car. 
- [x] Data Input 
``` 
mutation { input: {
  userId: Int, 
  make: String, 
  model: String, 
  year: Int, 
  mpg: Int, 
  fuelType: String
} car { 
make 
model
year 
mpg
}
```
Extension: 
- [x] I see a list of cars I previously added on the New Car Form 
- [x] Data query: ``` { fetchUserCars(userId: Int) { make \n model \n year } } ```
- [x] Data returned: ``` { "data": { "fetchUserCars": [ { "make": String, "model": String, "year": Int } ] } } ```

**Comment by ETBassist** [comment] 2021-01-09 01:45
Duplicate of #17

**Closed** 2021-01-10 23:53 UTC
Labels: frontend
